### ISSUE TITLE
Some Noodle walls are transparent

### ISSUE THREAD

**Issue by etiennec78** [StackDoubleFlow/NoodleExtensions#37]
I am currently making a map using Scuffed Walls' TextToWalls function but since the first release of Noodle on Beat Saber 1.24, my walls are really dim and not clearly visible like on PC.
Since the version 1.2.4 of Noodle, the bug got worse. The walls are no longer dim but transparent.
I tried to change the settings of Noodle but my walls were still dim/transparent.

Pc Noodle (expected result)
![PCNoodle](https://user-images.githubusercontent.com/59794011/187020745-59ee19b4-469d-49cd-9b59-685ba1ed88ce.png)

Quest Noodle 1.2.2 (walls are dim)
![QuestNoodle_1_2_2](https://user-images.githubusercontent.com/59794011/187020746-4cd7e228-9f5b-4c0e-86c3-4748346412eb.jpg)

Quest Noodle 1.2.4 (walls are transparent)
![QuestNoodle_1_2_4](https://user-images.githubusercontent.com/59794011/187020748-b510eacd-d64a-47ce-968c-d31f5c218c35.jpg)

**Comment by Fernthedev** [comment]
Make your walls brighter (increase alpha)

**Comment by Fernthedev** [comment]
To add more details, you can look at `Foolish of me` as a reference for a map that has visible pure white walls. It uses `[10, 10, 10, 0]`, however, you should also try `[10, 10, 10, 1]` if that doesn't work.
The wall looks are not a Noodle issue because as you mentioned both solid and transparent walls don't look proper, which isn't a bug at all and instead how the walls simply look on Quest.

**Comment by etiennec78** [comment]
Thank you for your reply !
I asked for help on discord but no one found the issue.
I just tried it on my quest and it works great ! (the walls are really blocky but completely white)
Sorry for opening an issue for this.
Thanks again !
