### ISSUE TITLE
Failing at the song start

### ISSUE THREAD

**Issue by Nitai610** [StackDoubleFlow/NoodleExtensions#38]
Im failing when the song finish to load in Somewhere Out There https://beatsaver.com/maps/1e6ff 
I thought you fix it but now it still happening

**Comment by Fernthedev** [comment]
I did. That's no longer the case.

**Comment by Nitai610** [comment]
I disabled every mod except NE and chrome (and core mods) and still failing

**Comment by Nitai610** [comment]
Can you please check that again?

**Comment by Mattshark89** [comment]
I am getting this issue still as well. I used to fix it in 1.17.1 by pressing HOME so that the song pauses right at the start, but that doesn't work either as the game will freeze once you resume in 1.24. Only Somewhere Out There has this issue (as well as some texture glitches at the water scene, where most of the textures are just jet black)
